### ISSUE TITLE
Provide documentation about Eclipse ECA sign-off status

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/documentation#34]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

Adoptium and all it repos belong to the [Eclipse Foundation](https://www.eclipse.org) since Adoptium is a top level project at Eclipse. To contribute to an Eclipse project the[ Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) must be (digitally) signed. To do so an account at Eclipse is needed. The ECA is checked at GitHub in each pull request. Eclipse provides some general information regarding GIT and ECA but it would make sense to have a newcomer friendly documentation that is made directly for GitHub and pull requests.
Additional Information can be found [here](https://wiki.eclipse.org/Development_Resources/Handling_Git_Contributions) and [here](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git).
The goal of this issue is to provide a tutorial / step by step guide for newcomers as an adoc in this repo.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by MBoegers** [comment]
I'm on it
