### ISSUE TITLE
Documentation Community Meeting - 29 Nov 2021

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/documentation#35]
This is the agenda and documentation of a [community meeting](https://github.com/adoptium/documentation/wiki/Adoptium-documentation-community-meetings) for the Adoptium homepage and documentation. If you plan to attend please leave a comment in this issue :)

## 📌 Date
We will meet on Monday, 29 Nov. 2021 at 16:30 GMT+2 (Germany/Berlin).
For the meeting use Google Meet: [Link to the meeting](https://meet.google.com/vef-thgd-okf)

## 📄 Agenda
- Discuss coding rules (examples: https://github.com/rico-projects/rico/blob/master/JAVA_STYLE_GUIDE.md, https://google.github.io/styleguide/javaguide.html)
- Discuss formatting rules / should we provide https://editorconfig.org support?
- Discuss test workflow rules (given-when-then)
- Milestone 1 of documentation service (https://github.com/adoptium/documentation-services/pull/42)
- Review of the service architecture (https://github.com/adoptium/documentation-services)
- Discuss Microprofile usage ([at]Singleton, https://github.com/mirkosertic/cdicron)
- Open topics: Codacy, new issues, pair programming sessions?

## 👥 How to attend?
The meeting is open for everyone :) If you want to contribute to the Adoptium documentation or just want to know what we are doing just [join the meeting](https://meet.google.com/vef-thgd-okf). If possible please add a short comment to this issue that you plan to attend the meeting. This meeting is managed in the [Adoptium Community calendar](https://calendar.google.com/calendar/embed?src=c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com). An ICAL link to integrate the calendar in other tools can be found [here](https://calendar.google.com/calendar/ical/c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com/public/basic.ics). If you plan to attend please leave a comment in this issue :)

## 🆕🐥 Newcomer support
We assume that this project is a very good opportunity to start with open source contributions. Therefore we always provide several "good first" issues. More information can be found [here](https://github.com/adoptium/documentation/wiki/Newcomer-Support).

## 🎉 Achievements since last meeting
- PR https://github.com/adoptium/documentation/pull/18 merged
- PR https://github.com/adoptium/documentation-services/pull/23 merged
- PR https://github.com/adoptium/documentation-services/pull/24 merged
- PR https://github.com/adoptium/documentation-services/pull/25 merged
- PR https://github.com/adoptium/documentation-services/pull/26 merged
- Projects setup in Codacy: https://app.codacy.com/gh/adoptium/documentation-services/ 
- PR https://github.com/adoptium/documentation-services/pull/33 merged
- PR https://github.com/adoptium/documentation-services/pull/31 merged
- PR https://github.com/adoptium/documentation-services/pull/29 merged
- PR https://github.com/adoptium/documentation/pull/38 merged

## ✏️ Minutes
- We will plan bi-weekly pair programming sessions
- **Milestone 1** will be reached with the merge of https://github.com/adoptium/documentation-services/pull/42
- **Milestone 2** will be a hosted service that is ready for integration in [adoptium.net](https://adoptium.net/)
- Code formating, Coding rules & test workflows: We will add some definitions to contibutions.md (links), we like hoe we currently work and will continue

**Comment by MBoegers** [comment]
I am with you today

**Comment by vanross** [comment]
me too

**Comment by hendrikebbers** [comment]
@MBoegers can you send me (hendrik.ebbers at web.de or twitter [at]hendrikebbers) your contact information for the pair programming doodle.
