### ISSUE TITLE
Documentation for ZenHub

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/documentation#39]
We need a documentation and "getting started" guide regarding our ZenHub board for newcomers.

**Comment by hendrikebbers** [comment]
Link to ZenHub: https://app.zenhub.com

**Comment by hendrikebbers** [comment]
What needs to be documented:
- How to access the project board at ZenHub
- The basic workflow that is used by the team
- How milestones are handled

**Comment by smlambert** [comment]
I will close this as we seem to be moving towards using Github organizational projects for managing the various projects and releases we have.
